### ISSUE TITLE
replacement

### ISSUE THREAD

**Issue by keradus** [nilportugues/php_backslasher#12]
Hi !
Idea behind this package is really great!

This package is not actively maintained, and
some time ago, one of open-source contributor bring this feature into https://github.com/FriendsOfPHP/PHP-CS-Fixer/ as `native_function_invocation` rule.

Maybe you want to deprecate this package and redirect users to PHP CS Fixer to not need to maintain this package ?

**Comment by ksom** [comment]
@keradus 
Hi !

I see just one difference between them. This one backslash php constant also \true \null \false when FOP/php-cs-fixer doesn't do it, it only do it for native function call.

I would like to know if this is effective. I tend to think that add backslash on true, false and null appears to me overkill. What about constant like PHP_EOL DIRECTORY_SEPARATOR and all other native constant?

**Comment by keradus** [comment]
usually you don't backslash everything in code as is. you either backslash what's crucial for your app, or you backslash everything in artifact build job

**Comment by ksom** [comment]
@keradus Thanks for your response :) I will go to php-cs-fixer than, that's only backslash native function. But doesn't backslash constants.

**Comment by nilportugues** [comment]
Nice point. When this code was written php-cs-fixer did not have this feature.
