### ISSUE TITLE
Improvement: add switch to inteoduce 'use' statements for functions instead of backslash

### ISSUE THREAD

**Issue by gggeek** [nilportugues/php_backslasher#13]
It can be argued that code would be kept cleaner by adding at the top of the modified file 'use' statements for each of the optimizeable functions instead of backslashes in the calls.

**Comment by nilportugues** [comment]
I agree, but it's not cleanness what this code is aiming for, but (micro) performance optimization. 

Loading a class in the use, makes it loaded beforehand, not when needed down the lines.
