### ISSUE TITLE
Consider adding some bechmarks to show the speed gain

### ISSUE THREAD

**Issue by javiereguiluz** [nilportugues/php_backslasher#4]
The README states that: _"[...] and therefore execution is faster"_. It would be nice to have some bechmarks or profile comparisons showing that difference in real world applications (Symfony, Drupal, etc.)

**Comment by nilportugues** [comment]
I was planning to do this ... I believe frameworks would make the most out of this rather than libraries.

**Comment by keradus** [comment]
any news perhaps ?

**Comment by rybakit** [comment]
Just FYI, I ran a _synthetic_ benchmark against the [msgpack.php](https://github.com/rybakit/msgpack.php) library and noticed a small performance improvement: https://github.com/rybakit/msgpack.php/pull/8.
