### ISSUE TITLE
Booleans

### ISSUE THREAD

**Issue by mrsimonbennett** [nilportugues/php_backslasher#7]
Maybe do this for booleans too. Adds one less call. 

https://3v4l.org/cqCno/vld#tabs ops = 7

https://3v4l.org/k5lL1/vld#tabs ops = 8

**Comment by mrsimonbennett** [comment]
Oh sorry you already did this :)

**Comment by nilportugues** [comment]
@mrsimonbennett still thanks :D! :+1:

**Comment by BenMorel** [comment]
@mrsimonbennett Just out of curiosity, what was the extra opcode involved?
I can't reproduce using your links, PHP 7.1 opcodes are now the same for both versions.

Also, what's different between using `\true` and `true`? AFAIK, you can't redefine this value, so I can't see the point of having `\true` at all...
